name: earcopy-env
channels:
  - conda-forge
dependencies:
  - python=3.8
  - ffmpeg
  - cython
  - numpy=1.19.5
  - pip
  - pip:
    - numpy==1.19.5
    - madmom
    - demucs
    - omnizart
    - pretty_midi
    - pandas
    - protobuf==3.20.0
    - typing-extensions
    - streamlit